FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm i -g npm
RUN npm i --only=production
RUN npm i -g babel-cli
RUN npm i babel-plugin-transform-runtime
COPY . .
RUN npm run build
ENV NODE_ENV production

EXPOSE 80
